// flow-typed signature: aef5eee46805f62708570636d602cabd
// flow-typed version: <<STUB>>/forerunnerdb_v^1.4.40/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'forerunnerdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'forerunnerdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'forerunnerdb/chrome-extension/bootstrap/js/bootstrap' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/bootstrap/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/bootstrap/js/npm' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/devtools' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/bootstrap-treeview' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-all' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-all.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-angular.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-autobind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-autobind.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-core.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-core+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-core+views.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-core+views+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-infinilist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/fdb-legacy.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/jquery-2.1.4.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/jquery.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/js/jsrender-helpers' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/panel' {
  declare module.exports: any;
}

declare module 'forerunnerdb/chrome-extension/sidebar' {
  declare module.exports: any;
}

declare module 'forerunnerdb/coverage/minified/prettify' {
  declare module.exports: any;
}

declare module 'forerunnerdb/coverage/minified/sorter' {
  declare module.exports: any;
}

declare module 'forerunnerdb/coverage/source/prettify' {
  declare module.exports: any;
}

declare module 'forerunnerdb/coverage/source/sorter' {
  declare module.exports: any;
}

declare module 'forerunnerdb/doc/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'forerunnerdb/doc/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'forerunnerdb/doc/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'forerunnerdb/gruntfile' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/gulpfile' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/hooks/after_prepare/010_add_platform_class' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/app' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/app/index/_routes' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/app/index/index' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/app/index/settings' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/app/item/_routes' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/app/item/detail' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/app/item/itemList' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/controllers' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/directives' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/routes' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/js/services' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-all' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-all.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-angular.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-autobind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-autobind.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-infinilist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-infinilist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-legacy' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-legacy.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular-ui/angular-ui-router' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular-ui/angular-ui-router.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-animate' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-animate.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-resource' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-resource.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-sanitize' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-sanitize.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic-angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic-angular.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.bundle' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.bundle.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/ionicExampleServer/server' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/all' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/autobind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/core' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/core+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/core+views' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/core+views+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/infinilist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/legacy' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/builds/nodecore' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-all' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-all.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-angular.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-autobind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-autobind.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core+views' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core+views.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core+views+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-core+views+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-infinilist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-infinilist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-legacy' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/dist/fdb-legacy.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/ActiveBucket' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/AutoBind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/BinaryLog' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/BinaryTree' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Collection' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/CollectionGroup' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Condition' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Core' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Db' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Document' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/GeoHash' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Grid' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Highchart' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Index2d' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/IndexBinaryTree' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/IndexHashMap' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Infinilist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/KeyValueStore' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Metrics' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.ChainReactor' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Common' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Constants' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.CRUD' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Events' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Matching' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Sorting' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Tags' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Triggers' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Mixin.Updating' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/NodeApiClient' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/NodeApiServer' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/NodePersist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/NodeRAS' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Odm' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/OldView.Bind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/OldView' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Operation' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Overload' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Overview' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Path' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/PersistCompress' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/PersistCrypto' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Procedure' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/ReactorIO' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Remote' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Rest' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Section' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Serialiser' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Server' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Shared' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/Shim.IE8' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/SkeletonModule' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/vendor/jsviews' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/lib/View' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/astrobench/dist/astrobench' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/astrobench/dist/astrobench.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/astrobench/examples/bench' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/astrobench/gulpfile' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/astrobench/src/astrobench' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/astrobench/src/ui' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-all' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-all.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-angular.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-autobind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-autobind.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-infinilist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-infinilist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-legacy' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/lib/fdb-legacy.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/perfTests/Serialiser.bench' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/tonic/example' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/base' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/data' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/blanket.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-all' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-all.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-angular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-angular.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-autobind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-autobind.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views+persist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views+persist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-infinilist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-infinilist.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-legacy' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/fdb-legacy.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/highcharts-all' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/jquery-1.11.0.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/jquery-2.1.4.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/jsrender-helpers' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/lie.polyfill.min' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/multiselect/js/bootstrap-multiselect' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/polyfiller' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/lib/qunit' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/nodeTests' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsActiveBucket' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsAngular' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsAutoBind' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsBinaryTree' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsCollection' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsCollectionGroup' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsCollectionGroupToViewChain' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsCollectionToCollectionGroupChain' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsCollectionToViewChain' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsCore' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsDb' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsDocument' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsEvents' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsGrid' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsHighCharts' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsIndex2d' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsIndexBinaryTree' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsIndexHashMap' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsLocalforage' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsNodeApi' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsOverload' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsOverview' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsPaging' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsPerformance' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsPersist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsRest' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsSerialiser' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsSorting' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsTags' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsTransform' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsTrigger' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsViewBasicCRUD' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsViewComplexCRUD' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsViewGeneral' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/unitTests/tests/testsViewQueriedCRUD' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/geospatialMap' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/grid' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/highchart' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/infinilist' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/infinilist2' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/infinilist3' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/mapLabel' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/nodeApiClient' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/nodeApiServer' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/transform' {
  declare module.exports: any;
}

declare module 'forerunnerdb/js/useTests/js/views' {
  declare module.exports: any;
}

declare module 'forerunnerdb/out/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'forerunnerdb/out/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'forerunnerdb/out/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'forerunnerdb/postinstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'forerunnerdb/chrome-extension/bootstrap/js/bootstrap.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/bootstrap/js/bootstrap'>;
}
declare module 'forerunnerdb/chrome-extension/bootstrap/js/bootstrap.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/bootstrap/js/bootstrap.min'>;
}
declare module 'forerunnerdb/chrome-extension/bootstrap/js/npm.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/bootstrap/js/npm'>;
}
declare module 'forerunnerdb/chrome-extension/devtools.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/devtools'>;
}
declare module 'forerunnerdb/chrome-extension/js/bootstrap-treeview.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/bootstrap-treeview'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-all.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-all'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-all.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-all.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-angular.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-angular.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-autobind.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-autobind'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-autobind.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-autobind.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-core.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-core.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-core+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-core+persist.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-core+views.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-core+views.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-core+views+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-core+views+persist.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-infinilist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-infinilist.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/fdb-legacy.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/fdb-legacy.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/jquery-2.1.4.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/jquery-2.1.4.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/jquery.min.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/jquery.min'>;
}
declare module 'forerunnerdb/chrome-extension/js/jsrender-helpers.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/js/jsrender-helpers'>;
}
declare module 'forerunnerdb/chrome-extension/panel.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/panel'>;
}
declare module 'forerunnerdb/chrome-extension/sidebar.js' {
  declare module.exports: $Exports<'forerunnerdb/chrome-extension/sidebar'>;
}
declare module 'forerunnerdb/coverage/minified/prettify.js' {
  declare module.exports: $Exports<'forerunnerdb/coverage/minified/prettify'>;
}
declare module 'forerunnerdb/coverage/minified/sorter.js' {
  declare module.exports: $Exports<'forerunnerdb/coverage/minified/sorter'>;
}
declare module 'forerunnerdb/coverage/source/prettify.js' {
  declare module.exports: $Exports<'forerunnerdb/coverage/source/prettify'>;
}
declare module 'forerunnerdb/coverage/source/sorter.js' {
  declare module.exports: $Exports<'forerunnerdb/coverage/source/sorter'>;
}
declare module 'forerunnerdb/doc/scripts/linenumber.js' {
  declare module.exports: $Exports<'forerunnerdb/doc/scripts/linenumber'>;
}
declare module 'forerunnerdb/doc/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'forerunnerdb/doc/scripts/prettify/lang-css'>;
}
declare module 'forerunnerdb/doc/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'forerunnerdb/doc/scripts/prettify/prettify'>;
}
declare module 'forerunnerdb/gruntfile.js' {
  declare module.exports: $Exports<'forerunnerdb/gruntfile'>;
}
declare module 'forerunnerdb/ionicExampleClient/gulpfile.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/gulpfile'>;
}
declare module 'forerunnerdb/ionicExampleClient/hooks/after_prepare/010_add_platform_class.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/hooks/after_prepare/010_add_platform_class'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/app.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/app'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/app/index/_routes.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/app/index/_routes'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/app/index/index.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/app/index/index'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/app/index/settings.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/app/index/settings'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/app/item/_routes.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/app/item/_routes'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/app/item/detail.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/app/item/detail'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/app/item/itemList.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/app/item/itemList'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/controllers.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/controllers'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/directives.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/directives'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/routes.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/routes'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/js/services.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/js/services'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-all.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-all'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-all.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-all.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-angular.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-angular'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-angular.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-angular.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-autobind.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-autobind'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-autobind.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-autobind.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+persist'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+persist.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views+persist'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-core+views+persist.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-infinilist.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-infinilist'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-infinilist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-infinilist.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-legacy.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-legacy'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-legacy.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/forerunnerdb/js/dist/fdb-legacy.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular-ui/angular-ui-router.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular-ui/angular-ui-router'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular-ui/angular-ui-router.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular-ui/angular-ui-router.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-animate.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-animate'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-animate.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-animate.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-resource.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-resource'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-resource.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-resource.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-sanitize.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-sanitize'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-sanitize.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular-sanitize.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/angular/angular.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic-angular.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic-angular'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic-angular.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic-angular.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.bundle.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.bundle'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.bundle.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.bundle.min'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic'>;
}
declare module 'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.min.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleClient/www/lib/ionic/js/ionic.min'>;
}
declare module 'forerunnerdb/ionicExampleServer/server.js' {
  declare module.exports: $Exports<'forerunnerdb/ionicExampleServer/server'>;
}
declare module 'forerunnerdb/js/builds/all.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/all'>;
}
declare module 'forerunnerdb/js/builds/angular.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/angular'>;
}
declare module 'forerunnerdb/js/builds/autobind.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/autobind'>;
}
declare module 'forerunnerdb/js/builds/core.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/core'>;
}
declare module 'forerunnerdb/js/builds/core+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/core+persist'>;
}
declare module 'forerunnerdb/js/builds/core+views.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/core+views'>;
}
declare module 'forerunnerdb/js/builds/core+views+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/core+views+persist'>;
}
declare module 'forerunnerdb/js/builds/infinilist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/infinilist'>;
}
declare module 'forerunnerdb/js/builds/legacy.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/legacy'>;
}
declare module 'forerunnerdb/js/builds/nodecore.js' {
  declare module.exports: $Exports<'forerunnerdb/js/builds/nodecore'>;
}
declare module 'forerunnerdb/js/dist/fdb-all.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-all'>;
}
declare module 'forerunnerdb/js/dist/fdb-all.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-all.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-angular.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-angular'>;
}
declare module 'forerunnerdb/js/dist/fdb-angular.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-angular.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-autobind.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-autobind'>;
}
declare module 'forerunnerdb/js/dist/fdb-autobind.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-autobind.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-core.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core'>;
}
declare module 'forerunnerdb/js/dist/fdb-core.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-core+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core+persist'>;
}
declare module 'forerunnerdb/js/dist/fdb-core+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core+persist.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-core+views.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core+views'>;
}
declare module 'forerunnerdb/js/dist/fdb-core+views.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core+views.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-core+views+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core+views+persist'>;
}
declare module 'forerunnerdb/js/dist/fdb-core+views+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-core+views+persist.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-infinilist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-infinilist'>;
}
declare module 'forerunnerdb/js/dist/fdb-infinilist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-infinilist.min'>;
}
declare module 'forerunnerdb/js/dist/fdb-legacy.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-legacy'>;
}
declare module 'forerunnerdb/js/dist/fdb-legacy.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/dist/fdb-legacy.min'>;
}
declare module 'forerunnerdb/js/lib/ActiveBucket.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/ActiveBucket'>;
}
declare module 'forerunnerdb/js/lib/Angular.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Angular'>;
}
declare module 'forerunnerdb/js/lib/AutoBind.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/AutoBind'>;
}
declare module 'forerunnerdb/js/lib/BinaryLog.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/BinaryLog'>;
}
declare module 'forerunnerdb/js/lib/BinaryTree.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/BinaryTree'>;
}
declare module 'forerunnerdb/js/lib/Collection.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Collection'>;
}
declare module 'forerunnerdb/js/lib/CollectionGroup.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/CollectionGroup'>;
}
declare module 'forerunnerdb/js/lib/Condition.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Condition'>;
}
declare module 'forerunnerdb/js/lib/Core.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Core'>;
}
declare module 'forerunnerdb/js/lib/Db.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Db'>;
}
declare module 'forerunnerdb/js/lib/Document.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Document'>;
}
declare module 'forerunnerdb/js/lib/GeoHash.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/GeoHash'>;
}
declare module 'forerunnerdb/js/lib/Grid.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Grid'>;
}
declare module 'forerunnerdb/js/lib/Highchart.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Highchart'>;
}
declare module 'forerunnerdb/js/lib/Index2d.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Index2d'>;
}
declare module 'forerunnerdb/js/lib/IndexBinaryTree.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/IndexBinaryTree'>;
}
declare module 'forerunnerdb/js/lib/IndexHashMap.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/IndexHashMap'>;
}
declare module 'forerunnerdb/js/lib/Infinilist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Infinilist'>;
}
declare module 'forerunnerdb/js/lib/KeyValueStore.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/KeyValueStore'>;
}
declare module 'forerunnerdb/js/lib/Metrics.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Metrics'>;
}
declare module 'forerunnerdb/js/lib/Mixin.ChainReactor.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.ChainReactor'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Common.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Common'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Constants.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Constants'>;
}
declare module 'forerunnerdb/js/lib/Mixin.CRUD.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.CRUD'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Events.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Events'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Matching.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Matching'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Sorting.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Sorting'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Tags.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Tags'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Triggers.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Triggers'>;
}
declare module 'forerunnerdb/js/lib/Mixin.Updating.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Mixin.Updating'>;
}
declare module 'forerunnerdb/js/lib/NodeApiClient.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/NodeApiClient'>;
}
declare module 'forerunnerdb/js/lib/NodeApiServer.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/NodeApiServer'>;
}
declare module 'forerunnerdb/js/lib/NodePersist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/NodePersist'>;
}
declare module 'forerunnerdb/js/lib/NodeRAS.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/NodeRAS'>;
}
declare module 'forerunnerdb/js/lib/Odm.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Odm'>;
}
declare module 'forerunnerdb/js/lib/OldView.Bind.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/OldView.Bind'>;
}
declare module 'forerunnerdb/js/lib/OldView.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/OldView'>;
}
declare module 'forerunnerdb/js/lib/Operation.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Operation'>;
}
declare module 'forerunnerdb/js/lib/Overload.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Overload'>;
}
declare module 'forerunnerdb/js/lib/Overview.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Overview'>;
}
declare module 'forerunnerdb/js/lib/Path.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Path'>;
}
declare module 'forerunnerdb/js/lib/Persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Persist'>;
}
declare module 'forerunnerdb/js/lib/PersistCompress.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/PersistCompress'>;
}
declare module 'forerunnerdb/js/lib/PersistCrypto.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/PersistCrypto'>;
}
declare module 'forerunnerdb/js/lib/Procedure.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Procedure'>;
}
declare module 'forerunnerdb/js/lib/ReactorIO.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/ReactorIO'>;
}
declare module 'forerunnerdb/js/lib/Remote.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Remote'>;
}
declare module 'forerunnerdb/js/lib/Rest.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Rest'>;
}
declare module 'forerunnerdb/js/lib/Section.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Section'>;
}
declare module 'forerunnerdb/js/lib/Serialiser.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Serialiser'>;
}
declare module 'forerunnerdb/js/lib/Server.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Server'>;
}
declare module 'forerunnerdb/js/lib/Shared.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Shared'>;
}
declare module 'forerunnerdb/js/lib/Shim.IE8.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/Shim.IE8'>;
}
declare module 'forerunnerdb/js/lib/SkeletonModule.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/SkeletonModule'>;
}
declare module 'forerunnerdb/js/lib/vendor/jsviews.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/vendor/jsviews'>;
}
declare module 'forerunnerdb/js/lib/View.js' {
  declare module.exports: $Exports<'forerunnerdb/js/lib/View'>;
}
declare module 'forerunnerdb/js/perfTests/lib/astrobench/dist/astrobench.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/astrobench/dist/astrobench'>;
}
declare module 'forerunnerdb/js/perfTests/lib/astrobench/dist/astrobench.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/astrobench/dist/astrobench.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/astrobench/examples/bench.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/astrobench/examples/bench'>;
}
declare module 'forerunnerdb/js/perfTests/lib/astrobench/gulpfile.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/astrobench/gulpfile'>;
}
declare module 'forerunnerdb/js/perfTests/lib/astrobench/src/astrobench.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/astrobench/src/astrobench'>;
}
declare module 'forerunnerdb/js/perfTests/lib/astrobench/src/ui.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/astrobench/src/ui'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-all.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-all'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-all.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-all.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-angular.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-angular'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-angular.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-angular.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-autobind.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-autobind'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-autobind.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-autobind.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core+persist'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core+persist.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core+views'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core+views.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core+views+persist'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-core+views+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-core+views+persist.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-infinilist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-infinilist'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-infinilist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-infinilist.min'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-legacy.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-legacy'>;
}
declare module 'forerunnerdb/js/perfTests/lib/fdb-legacy.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/lib/fdb-legacy.min'>;
}
declare module 'forerunnerdb/js/perfTests/Serialiser.bench.js' {
  declare module.exports: $Exports<'forerunnerdb/js/perfTests/Serialiser.bench'>;
}
declare module 'forerunnerdb/js/tonic/example.js' {
  declare module.exports: $Exports<'forerunnerdb/js/tonic/example'>;
}
declare module 'forerunnerdb/js/unitTests/base.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/base'>;
}
declare module 'forerunnerdb/js/unitTests/data.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/data'>;
}
declare module 'forerunnerdb/js/unitTests/lib/blanket.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/blanket.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-all.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-all'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-all.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-all.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-angular.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-angular'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-angular.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-angular.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-autobind.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-autobind'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-autobind.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-autobind.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core+persist'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core+persist.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core+views'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core+views.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views+persist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core+views+persist'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-core+views+persist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-core+views+persist.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-infinilist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-infinilist'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-infinilist.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-infinilist.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-legacy.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-legacy'>;
}
declare module 'forerunnerdb/js/unitTests/lib/fdb-legacy.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/fdb-legacy.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/highcharts-all.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/highcharts-all'>;
}
declare module 'forerunnerdb/js/unitTests/lib/jquery-1.11.0.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/jquery-1.11.0.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/jquery-2.1.4.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/jquery-2.1.4.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/jsrender-helpers.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/jsrender-helpers'>;
}
declare module 'forerunnerdb/js/unitTests/lib/lie.polyfill.min.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/lie.polyfill.min'>;
}
declare module 'forerunnerdb/js/unitTests/lib/multiselect/js/bootstrap-multiselect.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/multiselect/js/bootstrap-multiselect'>;
}
declare module 'forerunnerdb/js/unitTests/lib/polyfiller.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/polyfiller'>;
}
declare module 'forerunnerdb/js/unitTests/lib/qunit.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/lib/qunit'>;
}
declare module 'forerunnerdb/js/unitTests/tests/nodeTests.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/nodeTests'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsActiveBucket.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsActiveBucket'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsAngular.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsAngular'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsAutoBind.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsAutoBind'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsBinaryTree.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsBinaryTree'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsCollection.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsCollection'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsCollectionGroup.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsCollectionGroup'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsCollectionGroupToViewChain.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsCollectionGroupToViewChain'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsCollectionToCollectionGroupChain.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsCollectionToCollectionGroupChain'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsCollectionToViewChain.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsCollectionToViewChain'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsCore.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsCore'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsDb.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsDb'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsDocument.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsDocument'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsEvents.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsEvents'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsGrid.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsGrid'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsHighCharts.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsHighCharts'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsIndex2d.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsIndex2d'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsIndexBinaryTree.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsIndexBinaryTree'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsIndexHashMap.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsIndexHashMap'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsLocalforage.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsLocalforage'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsNodeApi.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsNodeApi'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsOverload.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsOverload'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsOverview.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsOverview'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsPaging.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsPaging'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsPerformance.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsPerformance'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsPersist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsPersist'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsRest.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsRest'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsSerialiser.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsSerialiser'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsSorting.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsSorting'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsTags.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsTags'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsTransform.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsTransform'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsTrigger.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsTrigger'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsViewBasicCRUD.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsViewBasicCRUD'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsViewComplexCRUD.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsViewComplexCRUD'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsViewGeneral.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsViewGeneral'>;
}
declare module 'forerunnerdb/js/unitTests/tests/testsViewQueriedCRUD.js' {
  declare module.exports: $Exports<'forerunnerdb/js/unitTests/tests/testsViewQueriedCRUD'>;
}
declare module 'forerunnerdb/js/useTests/js/geospatialMap.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/geospatialMap'>;
}
declare module 'forerunnerdb/js/useTests/js/grid.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/grid'>;
}
declare module 'forerunnerdb/js/useTests/js/highchart.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/highchart'>;
}
declare module 'forerunnerdb/js/useTests/js/infinilist.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/infinilist'>;
}
declare module 'forerunnerdb/js/useTests/js/infinilist2.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/infinilist2'>;
}
declare module 'forerunnerdb/js/useTests/js/infinilist3.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/infinilist3'>;
}
declare module 'forerunnerdb/js/useTests/js/mapLabel.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/mapLabel'>;
}
declare module 'forerunnerdb/js/useTests/js/nodeApiClient.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/nodeApiClient'>;
}
declare module 'forerunnerdb/js/useTests/js/nodeApiServer.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/nodeApiServer'>;
}
declare module 'forerunnerdb/js/useTests/js/transform.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/transform'>;
}
declare module 'forerunnerdb/js/useTests/js/views.js' {
  declare module.exports: $Exports<'forerunnerdb/js/useTests/js/views'>;
}
declare module 'forerunnerdb/out/scripts/linenumber.js' {
  declare module.exports: $Exports<'forerunnerdb/out/scripts/linenumber'>;
}
declare module 'forerunnerdb/out/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'forerunnerdb/out/scripts/prettify/lang-css'>;
}
declare module 'forerunnerdb/out/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'forerunnerdb/out/scripts/prettify/prettify'>;
}
declare module 'forerunnerdb/postinstall.js' {
  declare module.exports: $Exports<'forerunnerdb/postinstall'>;
}
