// flow-typed signature: 245f8c7db51be3e9453df9eaabd6f7fa
// flow-typed version: <<STUB>>/rodal_v^1.5.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rodal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rodal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rodal/lib/rodal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rodal/lib/rodal.js' {
  declare module.exports: $Exports<'rodal/lib/rodal'>;
}
